### ISSUE TITLE
Deprecate in favor of sanctuary-type-classes?

### ISSUE THREAD

**Issue by safareli** [fantasyland/fantasy-sorcery#9]
Hey folks what if we deprecate/remove this module in favor of [sanctuary-type-classes][1]?

/cc @fantasyland/core

[1]: https://github.com/sanctuary-js/sanctuary-type-classes

**Comment by 5outh** [comment]
I'm cool with that. Since sanctuary-type-classes is pretty tightly coupled with the fantasy land spec, I'd also be happy to move it the `fantasyland` namespace, if that's something David wants to consider.

**Comment by davidchambers** [comment]
Moving @sanctuary-js projects to @fantasyland doesn't feel right to me.

The Fantasy Land spec is extremely important; I'm very grateful to Brian for creating it and to the many people who've contributed to it over the past few years.

Many of the other @fantasyland projects are experimental and/or undocumented and/or not actively maintained. There are several @sanctuary-js projects in this category, but the main ones are actively maintained, have test suites and documentation, and run in browsers without preprocessing or shims.

I'd like to see this issue resolved via the addition of a readme which links to [sanctuary-type-classes][1]. I'll submit a pull request for this if there's support for the idea.


[1]: https://github.com/sanctuary-js/sanctuary-type-classes

**Comment by SimonRichardson** [comment]
I'm no longer maintaining any fantasy land code. Do with it as you please :+1:
